### ISSUE TITLE
the addon doesn't load

### ISSUE THREAD

**Issue by aryanchoudharypro** [w-sx/virtualKeyboard#1]
Error importing global plugin virtualKeyboard Traceback (most recent call last):   File "globalPluginHandler.pyc", line 23, in listPlugins   File "importlib\__init__.pyc", line 126, in import_module   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 940, in exec_module   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed   File "C:\Users\aryan\AppData\Roaming\nvda\addons\virtualKeyboard\globalPlugins\virtualKeyboard.py", line 17, in <module>     class GlobalPlugin(globalPluginHandler.GlobalPlugin):   File "C:\Users\aryan\AppData\Roaming\nvda\addons\virtualKeyboard\globalPlugins\virtualKeyboard.py", line 27, in GlobalPlugin     key('y'): key('numpadDivide'),     ^^^^^^^^   File "C:\Users\aryan\AppData\Roaming\nvda\addons\virtualKeyboard\globalPlugins\virtualKeyboard.py", line 14, in key     kig = KeyboardInputGesture.fromName(name)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "keyboardHandler.pyc", line 686, in fromName   File "winUser.pyc", line 712, in VkKeyScanEx LookupError

**Comment by w-sx** [comment]
Thanks for the Issue, the issue has been resolved in #2 . Sorry for not viewing this in time.
